=== impierce/credential-converter/json/ebsi-elm/vcdm2.0-attestation-schema/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EBSI Verifiable Attestation",
  "description": "The schema defines a generic structure for any EBSI-related Verifiable Credentials according to the VCDM v2.0",
  "type": "object",
  "properties": {
    "@context": {
      "description": "Semantic context for the issued credential. First element MUST be https://www.w3.org/ns/credentials/v2",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "contains": {
        "const": "https://www.w3.org/ns/credentials/v2"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "id": {
      "description": "Globally unique identifier for the issued credential. It can be a UUID or another globally unique identifier.",
      "type": "string",
      "format": "uri"
    },
    "type": {
      "description": "Full type chain, used to identify the credential base types",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "issuer": {
      "description": "DID of the credential issuer",
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "object",
          "required": ["id"],
          "properties": {
            "id": {
              "description": "DID of the credential issuer",
              "type": "string",
              "format": "uri"
            }
          }
        }
      ]
    },
    "validFrom": {
      "description": "Defines the earliest point when the credential becomes valid.",
      "type": "string",
      "format": "date-time"
    },
    "validUntil": {
      "description": "Defines the latest point when the credential ceases to be valid.",
      "type": "string",
      "format": "date-time"
    },
    "credentialSubject": {
      "anyOf": [
        {
          "$ref": "#/$defs/credentialSubject"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialSubject"
          }
        }
      ]
    },
    "credentialStatus": {
      "description": "Defines suspension and/or revocation details for the issued credential. Further redefined by the type extension",
      "anyOf": [
        {
          "$ref": "#/$defs/credentialStatus"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialStatus"
          }
        }
      ]
    },
    "credentialSchema": {
      "description": "One or more schemas that validate the Verifiable Credential.",
      "anyOf": [
        {
          "$ref": "#/$defs/credentialSchema"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialSchema"
          }
        }
      ]
    },
    "termsOfUse": {
      "anyOf": [
        {
          "$ref": "#/$defs/termsOfUse"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/termsOfUse"
          }
        }
      ]
    },
    "evidence": {
      "anyOf": [
        {
          "$ref": "#/$defs/evidence"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/evidence"
          }
        }
      ]
    },
    "relatedResource": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "URL the integrity information is for",
            "type": "string",
            "format": "uri"
          },
          "mediaType": {
            "description": "Expected media type for the indicated resource",
            "type": "string"
          }
        },
        "required": ["id"],
        "anyOf": [
          {
            "properties": {
              "digestSRI": {
                "description": "Digest value of Subresource Integrity",
                "type": "string"
              }
            },
            "required": ["digestSRI"]
          },
          {
            "properties": {
              "digestMultibase": {
                "description": "Digest value of multihash encoded in multibase.",
                "type": "string"
              }
            },
            "required": ["digestMultibase"]
          }
        ]
      }
    }
  },
  "required": [
    "@context",
    "id",
    "type",
    "issuer",
    "validFrom",
    "credentialSubject",
    "credentialSchema"
  ],
  "$defs": {
    "credentialSubject": {
      "description": "Defines information about the subject that is defined by the type chain",
      "type": "object",
      "properties": {
        "id": {
          "description": "Defines the DID of the subject that is described by the issued credential",
          "type": "string",
          "format": "uri"
        }
      }
    },
    "credentialStatus": {
      "description": "Defines suspension and/or revocation details for the issued credential. Further redefined by the type extension",
      "type": "object",
      "properties": {
        "id": {
          "description": "Exact identity for the credential status",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the revocation type extension",
          "type": "string"
        }
      },
      "required": ["id", "type"]
    },
    "credentialSchema": {
      "description": "Contains information about the credential schema on which the issued credential is based",
      "type": "object",
      "properties": {
        "id": {
          "description": "References the credential schema stored on the Trusted Schemas Registry (TSR)",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines credential schema type",
          "type": "string"
        }
      },
      "required": ["id", "type"]
    },
    "termsOfUse": {
      "description": "Contains the terms under which the issued credential was issued",
      "type": "object",
      "properties": {
        "id": {
          "description": "Contains a URL that points to where more information about this instance of terms of use can be found.",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the type extension",
          "type": "string"
        }
      },
      "required": ["type"]
    },
    "evidence": {
      "type": "object",
      "properties": {
        "id": {
          "description": "If present, it MUST contain a URL that points to where more information about this instance of evidence can be found.",
          "type": "string"
        },
        "type": {
          "anyOf": [
            {
              "description": "Defines the evidence type extension",
              "type": "string"
            },
            {
              "description": "Defines the evidence type extension",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        }
      },
      "required": ["type"]
    }
  }
}

=== impierce/credential-converter/json/output/example_OBv3_to_ELM.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "http://data.europa.eu/snb/model/context/edc-ap"
  ],
  "credentialSchema": [
    {
      "id": "http://data.europa.eu/snb/model/ap/edc-generic-full",
      "type": "ShaclValidator2017"
    },
    {
      "id": "https://api-pilot.ebsi.eu/trusted-schemas-registry/v3/schemas/0x7ff3bc76bd5e37b3d29721b8698646a722a24a4f4ab0a0ba63d4bbbe0ef9758d",
      "type": "JsonSchema"
    }
  ],
  "credentialSubject": {
    "hasClaim": [
      {
        "id": "urn:epass:learningAchievement:6",
        "specifiedBy": {
          "title": {
            "en": [
              "German International Abitur"
            ]
          }
        },
        "title": {
          "en": [
            "Higher  Education Entrance Qualification - German International ABITUR School"
          ]
        }
      }
    ],
    "id": "did:key:afsdlkj34134",
    "identifier": {
      "id": "urn:epass:identifier:2",
      "notation": "5547554",
      "schemeName": "Student ID",
      "type": "Identifier"
    }
  },
  "id": "urn:credential:87ddce4d-de74-4838-b7a4-1f14d9c614ec",
  "issuer": {
    "id": "did:ebsi:org:12345689",
    "legalName": {
      "en": "ORGANIZACION TEST"
    }
  },
  "type": [
    "VerifiableCredential",
    "OpenBadgeCredential"
  ],
  "validFrom": "2020-07-20T00:00:00+02:00"
}

=== impierce/credential-converter/json/ebsi-elm/vcdm2.0-attestation-schema/examples/generic-attestation.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
  "type": ["VerifiableCredential", "VerifiableAttestation"],
  "issuer": "did:ebsi:ziDnioxYYLW1a3qUbqTFz4W",
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbnTvvSLAcNJvfNeLNuB9Y3Mbhus5btx3CBNknmhSStgGbqhMkqfWNSYZ5Vd1A8xQdD948jQSEjShYE1SFe1wZSgsw5S4v6sfHVV2p6waDwh9hCjdWdjFUo3nyU1rYLbuZxg"
  },
  "credentialStatus": [
    {
      "id": "https://essif.europa.eu/status/45",
      "type": "AnyExtension"
    }
  ],
  "credentialSchema": [
    {
      "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v3/schemas/0xff4f1fa4f0efd4306a218f669c7482d8cfcc7a13ba44f34af69f41889704002a",
      "type": "JsonSchema"
    }
  ],
  "evidence": {
    "type": "CustomType"
  },
  "relatedResource": [
    {
      "id": "https://www.w3.org/ns/credentials/v2",
      "mediaType": "application/ld+json",
      "digestMultibase": "moLay0ut7BUL5IfvPTaE2QhqrtH5cU3mrf4fQb/MhrH5NhGh+oDwdoqE0AynGRjFJ"
    }
  ]
}
